services:
  email-service:
    build:
      context: .
      dockerfile: docker/go/Dockerfile
    container_name: email-service
    environment:
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - TO_ADDRESS=${TO_ADDRESS}
      - FROM_ADDRESS=${FROM_ADDRESS}
      - APP_PORT=${APP_PORT}
    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: email-proxy
    environment:
      - APP_PORT=${APP_PORT}
      - NGINX_PORT=${NGINX_PORT}
    ports:
      - "${HOST_PORT}:${NGINX_PORT}"
    volumes:
      - ./docker/nginx/nginx.template.conf:/etc/nginx/templates/nginx.template.conf:ro
      - ./docker/nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - "email-service"
    restart: unless-stopped