services:
  email-service:
    build: .
    ports:
      - "${HOST_PORT}:${APP_PORT}"
    environment:
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - TO_ADDRESS=${TO_ADDRESS}
      - FROM_ADDRESS=${FROM_ADDRESS}
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: email-proxy
    ports:
      - "${NGINX_ENTRY_PORT}:${NGINX_PORT}"
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - "email-service"
    restart: unless-stopped