services:
  email-service:
    build: .
    environment:
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - TO_ADDRESS=${TO_ADDRESS}
      - FROM_ADDRESS=${FROM_ADDRESS}
      - APP_PORT=${APP_PORT}
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: email-proxy
    environment:
      - APP_PORT=${APP_PORT}
      - NGINX_PORT=${NGINX_PORT}
    ports:
      - "${HOST_PORT}:${NGINX_PORT}"
    volumes:
      - ./nginx.template.conf:/etc/nginx/templates/nginx.template.conf:ro
    depends_on:
      - "email-service"
    restart: unless-stopped